hwm10/famous_quotes/famous_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quoteapp.urls")),
]

hwm10/famous_quotes/quoteapp/urls.py
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "quoteapp"

urlpatterns = [
    path("", views.QuoteHome.as_view(), name="home"),
    path("tag/", views.AddTag.as_view(), name="tag"),
    path("addquote/", views.addquote, name="addquote"),
    path("addauthor/", views.addauthor, name="addauthor"),
    path("post/<int:post_id>", views.ShowPost.as_view(), name="post"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(
            template_name="quoteapp/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="quoteapp/password_reset_confirm.html",
            success_url="/quoteapp/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "quoteapp/reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="quoteapp/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

hwm10/famous_quotes/quoteapp/models.py
from django.db import models
from django.shortcuts import render, redirect
from django.urls import reverse


class Quote(models.Model):
    quote = models.CharField(max_length=255, unique=True)
    author = models.ForeignKey("Author", on_delete=models.PROTECT)
    tag = models.ManyToManyField("Tag")
    time_create = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.quote}"

    def get_absolute_url(self):
        return reverse("quoteapp:post", kwargs={"post_id": self.pk})

    class Meta:
        verbose_name = "Famous quote"
        verbose_name_plural = "Famous quotes"
        ordering = ["time_create"]


class Author(models.Model):
    fullname = models.CharField(max_length=255, unique=True)
    born_date = models.CharField(max_length=20)
    born_location = models.CharField(max_length=50)
    description = models.TextField(null=True)

    def __str__(self) -> str:
        return f"{self.fullname}"

    def get_absolute_url(self):
        return reverse("quoteapp:post", kwargs={"post_id": self.pk})


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"

hwm10/famous_quotes/quoteapp/forms.py
from django.forms import (
    ModelForm,
    CharField,
    EmailField,
    EmailInput,
    TextInput,
    PasswordInput,
)
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


from .models import Tag, Quote, Author


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]


class QuoteForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["author"].empty_label = "Chose an author"

    class Meta:
        model = Quote
        fields = ["quote", "author", "tag"]
        widgets = {
            "quote": TextInput(attrs={"cols": 60, "rows": 10}),
        }


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class RegisterUserForm(UserCreationForm):

    username = CharField(label="Login", widget=TextInput(attrs={"class": "form-input"}))
    email = EmailField(label="Email", widget=EmailInput(attrs={"class": "form-input"}))
    password1 = CharField(
        label="Password", widget=PasswordInput(attrs={"class": "form-input"})
    )
    password2 = CharField(
        label="Password confirmation",
        widget=PasswordInput(attrs={"class": "form-input"}),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    username = CharField(label="Login", widget=TextInput(attrs={"class": "form-input"}))
    password = CharField(
        label="Password", widget=PasswordInput(attrs={"class": "form-input"})
    )

hwm10/famous_quotes/quoteapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin


from .models import Quote, Tag, Author
from .forms import TagForm, QuoteForm, AuthorForm, RegisterUserForm, LoginUserForm
from .utils import DataMixin


class QuoteHome(DataMixin, ListView):
    model = Quote
    template_name = "quoteapp/index.html"
    context_object_name = "quotes"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Quotes to Scrape")
        context = dict(list(context.items()) + list(c_def.items()))
        return context


class AddTag(LoginRequiredMixin, DataMixin, CreateView):
    form_class = TagForm
    template_name = "quoteapp/tag.html"
    # login_url = reverse_lazy("quoteapp:home") - альтернатива get_success_url
    raise_exception = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Add tag")
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def get_success_url(self):
        return reverse("quoteapp:home")

    # Вместо дублирования этой функции в разных классах можно указать
    # LOGIN_REDIRECT_URL = "/" в settings.py


def addquote(request):

    author = Author.objects.all()
    tags = Tag.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)

        if form.is_valid():
            new_quote = form.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist("tags"))

            for tag in choice_tags.iterator():
                new_quote.tag.add(tag)
            return redirect(to="quoteapp:home")

        else:
            return render(
                request,
                "quoteapp/addquote.html",
                {"form": form, "author": author, "tags": tags},
            )

    return render(
        request,
        "quoteapp/addquote.html",
        {"form": QuoteForm(), "author": author, "tags": tags},
    )


def addauthor(request):

    if request.method == "POST":
        form = AuthorForm(request.POST)

        if form.is_valid():
            try:
                form.save()
                return redirect(to="quoteapp:home")
            except:
                form.add_error(None, "Quote saving error")

        else:
            return render(
                request,
                "quoteapp/addquote.html",
                {"form": form},
            )

    return render(
        request,
        "quoteapp/addauthor.html",
        {"form": AuthorForm()},
    )


class ShowPost(DataMixin, DetailView):
    model = Author
    template_name = "quoteapp/post.html"
    pk_url_kwarg = "post_id"
    context_object_name = "post"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Post")
        context = dict(list(context.items()) + list(c_def.items()))
        return context


class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = "quoteapp/register.html"
    success_url = reverse_lazy("quoteapp:login")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Registration")
        context = dict(list(context.items()) + list(c_def.items()))
        return context

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("quoteapp:home")


class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = "quoteapp/login.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Log in")
        context = dict(list(context.items()) + list(c_def.items()))
        return context


def logoutuser(request):
    logout(request)
    return redirect(to="quoteapp:home")


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "quoteapp/password_reset.html"
    email_template_name = "quoteapp/password_reset_email.html"
    html_email_template_name = "quoteapp/password_reset_email.html"
    success_url = reverse_lazy("quoteapp:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "quoteapp/password_reset_subject.txt"

hwm10/famous_quotes/quoteapp/templates/quoteapp/about.html
{% extends "quoteapp/base.html" %}

{% block content %}

<main class="container">
    <h1>{{ title }}</h1>
</main>
<p>Different content</p>
{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/addauthor.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:addauthor' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add</button>
    <button type="reset">Reset</button>
</form>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/addquote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:addquote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required>
                {% for a in author %}
                <option value="{{a.fullname}}">{{a.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
        <link rel="shortcut icon" href="{% static 'quoteapp/img/favicon.ico' %}" type="image/x-icon">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'quoteapp/css/fontello.css' %}">
        <link rel="stylesheet" href="{% static 'quoteapp/css/styles.css' %}">
        <title>{{ title }}</title>
    </head>
    <body>

    {% block mainmenu %}
        <div class="container-sm">
            <ul id="mainmenu" class="mainmenu">
                {% for m in menu %}
                <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
                {% endfor %}
                {% if request.user.is_authenticated %}
                <li class="last">{{ user.username }} | <a href="{% url 'quoteapp:logout' %}">Log out</a></li>
                {% else %}
                <li class="last"><a href="{% url 'quoteapp:register' %}">Registration</a> | <a href="{% url 'quoteapp:login' %}">Log in</a></li>
                {% endif %}        
            </ul>
            <div class="clear"></div>
        </div>
    {% endblock mainmenu %}

    <div class="container-sm">

    {% block content %}
    {% endblock %}

    {% if page_obj.has_other_pages %}
    <nav class="list-pages">
        <ul>
            {% for p in paginator.page_range %}
            {% if page_obj.number == p %}
            <li class="page-num page-num-selected">{{ p }}</li>
            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
            <li>
                <a href="?page={{ p }}">{{ p }}</a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
    {% endif %}
    </div>

        <script src="{% static 'quoteapp/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

hwm10/famous_quotes/quoteapp/templates/quoteapp/index.html
{% extends "quoteapp/base.html" %}

{% block content %}

<main class="container">
    <h1>{{ title }}</h1>
</main>
<ul>
    {% for q in quotes %}
    <li>
        <h2>{{ q.quote }}</h2>
        <p>by {{ q.author }}</p>
        <p class="link-read-post"><a href="{{ q.author.get_absolute_url }}">About</a></p>
        {% for quo in q.tag.all %}
        <li>
            {{ quo.name }}
        </li>
        {% endfor %}
        <hr>
    </li>
    {% endfor %}
</ul>>
{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/login.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>{{ title }}</h1>

<form method="POST">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Log in</button>
    <div class="small text-center">
        <a href="{% url 'quoteapp:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
</form>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/password_reset.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/password_reset_complete.html
{% extends "quoteapp/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/password_reset_confirm.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/password_reset_done.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'quoteapp:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'quoteapp:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/post.html
{% extends "quoteapp/base.html" %}

{% block content %}

<h1>{{post.fullname}}</h1>

<p>{{post.born_date}}</p>
<p>{{post.born_location}}</p>

{{post.description|linebreaks}}

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/register.html
{% extends "quoteapp/base.html" %}

{% block content %}
<h1>{{ title }}</h1>

<form method="POST">
    {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <button type="submit">Registration</button>
</form>

{% endblock %}

hwm10/famous_quotes/quoteapp/templates/quoteapp/tag.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:tag' %}">
    {% csrf_token %}
    <div>
        <label>Enter tag name: {{ form.name }}</label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}